package domain;
// Generated 30-ago-2017 15:19:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cursos generated by hbm2java
 */
public class Cursos  implements java.io.Serializable {


     private int idCurso;
     private Estudiantes estudiantes;
     private Horario horario;
     private Profesores profesores;
     private String nombreCurso;
     private Integer idInstrumento;
     private Character estado;
     private Set<Estudiantes> estudianteses = new HashSet<Estudiantes>(0);

    public Cursos() {
    }

	
    public Cursos(int idCurso) {
        this.idCurso = idCurso;
    }
    public Cursos(int idCurso, Estudiantes estudiantes, Horario horario, Profesores profesores, String nombreCurso, Integer idInstrumento, Character estado, Set<Estudiantes> estudianteses) {
       this.idCurso = idCurso;
       this.estudiantes = estudiantes;
       this.horario = horario;
       this.profesores = profesores;
       this.nombreCurso = nombreCurso;
       this.idInstrumento = idInstrumento;
       this.estado = estado;
       this.estudianteses = estudianteses;
    }
   
    public int getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(int idCurso) {
        this.idCurso = idCurso;
    }
    public Estudiantes getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Estudiantes estudiantes) {
        this.estudiantes = estudiantes;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public Profesores getProfesores() {
        return this.profesores;
    }
    
    public void setProfesores(Profesores profesores) {
        this.profesores = profesores;
    }
    public String getNombreCurso() {
        return this.nombreCurso;
    }
    
    public void setNombreCurso(String nombreCurso) {
        this.nombreCurso = nombreCurso;
    }
    public Integer getIdInstrumento() {
        return this.idInstrumento;
    }
    
    public void setIdInstrumento(Integer idInstrumento) {
        this.idInstrumento = idInstrumento;
    }
    public Character getEstado() {
        return this.estado;
    }
    
    public void setEstado(Character estado) {
        this.estado = estado;
    }
    public Set<Estudiantes> getEstudianteses() {
        return this.estudianteses;
    }
    
    public void setEstudianteses(Set<Estudiantes> estudianteses) {
        this.estudianteses = estudianteses;
    }




}


