package domain;
// Generated 30-ago-2017 15:19:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiantes generated by hbm2java
 */
public class Estudiantes  implements java.io.Serializable {


     private int cedula;
     private Padre padre;
     private Usuarios usuarios;
     private Integer edad;
     private Character genero;
     private String dirreccion;
     private String nomEscuela;
     private Integer grado;
     private String adecuacion;
     private Integer telefono;
     private Integer celular;
     private String correo;
     private Character pagoMatricula;
     private Pagomensual pagomensual;
     private Set<Cursos> cursoses = new HashSet<Cursos>(0);
     private Set<Cursos> cursoses_1 = new HashSet<Cursos>(0);
     private Listaespera listaespera;

    public Estudiantes() {
    }

	
    public Estudiantes(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Estudiantes(Padre padre, Usuarios usuarios, Integer edad, Character genero, String dirreccion, String nomEscuela, Integer grado, String adecuacion, Integer telefono, Integer celular, String correo, Character pagoMatricula, Pagomensual pagomensual, Set<Cursos> cursoses, Set<Cursos> cursoses_1, Listaespera listaespera) {
       this.padre = padre;
       this.usuarios = usuarios;
       this.edad = edad;
       this.genero = genero;
       this.dirreccion = dirreccion;
       this.nomEscuela = nomEscuela;
       this.grado = grado;
       this.adecuacion = adecuacion;
       this.telefono = telefono;
       this.celular = celular;
       this.correo = correo;
       this.pagoMatricula = pagoMatricula;
       this.pagomensual = pagomensual;
       this.cursoses = cursoses;
       this.cursoses_1 = cursoses_1;
       this.listaespera = listaespera;
    }
   
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public Padre getPadre() {
        return this.padre;
    }
    
    public void setPadre(Padre padre) {
        this.padre = padre;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public Character getGenero() {
        return this.genero;
    }
    
    public void setGenero(Character genero) {
        this.genero = genero;
    }
    public String getDirreccion() {
        return this.dirreccion;
    }
    
    public void setDirreccion(String dirreccion) {
        this.dirreccion = dirreccion;
    }
    public String getNomEscuela() {
        return this.nomEscuela;
    }
    
    public void setNomEscuela(String nomEscuela) {
        this.nomEscuela = nomEscuela;
    }
    public Integer getGrado() {
        return this.grado;
    }
    
    public void setGrado(Integer grado) {
        this.grado = grado;
    }
    public String getAdecuacion() {
        return this.adecuacion;
    }
    
    public void setAdecuacion(String adecuacion) {
        this.adecuacion = adecuacion;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public Integer getCelular() {
        return this.celular;
    }
    
    public void setCelular(Integer celular) {
        this.celular = celular;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Character getPagoMatricula() {
        return this.pagoMatricula;
    }
    
    public void setPagoMatricula(Character pagoMatricula) {
        this.pagoMatricula = pagoMatricula;
    }
    public Pagomensual getPagomensual() {
        return this.pagomensual;
    }
    
    public void setPagomensual(Pagomensual pagomensual) {
        this.pagomensual = pagomensual;
    }
    public Set<Cursos> getCursoses() {
        return this.cursoses;
    }
    
    public void setCursoses(Set<Cursos> cursoses) {
        this.cursoses = cursoses;
    }
    public Set<Cursos> getCursoses_1() {
        return this.cursoses_1;
    }
    
    public void setCursoses_1(Set<Cursos> cursoses_1) {
        this.cursoses_1 = cursoses_1;
    }
    public Listaespera getListaespera() {
        return this.listaespera;
    }
    
    public void setListaespera(Listaespera listaespera) {
        this.listaespera = listaespera;
    }




}


