package domain;
// Generated 30-ago-2017 15:19:55 by Hibernate Tools 4.3.1



/**
 * Listaespera generated by hbm2java
 */
public class Listaespera  implements java.io.Serializable {


     private int idEstudiante;
     private Estudiantes estudiantes;
     private String descripcion;

    public Listaespera() {
    }

	
    public Listaespera(Estudiantes estudiantes) {
        this.estudiantes = estudiantes;
    }
    public Listaespera(Estudiantes estudiantes, String descripcion) {
       this.estudiantes = estudiantes;
       this.descripcion = descripcion;
    }
   
    public int getIdEstudiante() {
        return this.idEstudiante;
    }
    
    public void setIdEstudiante(int idEstudiante) {
        this.idEstudiante = idEstudiante;
    }
    public Estudiantes getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Estudiantes estudiantes) {
        this.estudiantes = estudiantes;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


