package domain;
// Generated 30-ago-2017 15:19:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Padre generated by hbm2java
 */
public class Padre  implements java.io.Serializable {


     private int cedula;
     private String nombre;
     private String apellidos;
     private Integer telefono;
     private Integer celular;
     private String correo;
     private String ocupacion;
     private String lugarTrabajo;
     private Set<Estudiantes> estudianteses = new HashSet<Estudiantes>(0);

    public Padre() {
    }

	
    public Padre(int cedula) {
        this.cedula = cedula;
    }
    public Padre(int cedula, String nombre, String apellidos, Integer telefono, Integer celular, String correo, String ocupacion, String lugarTrabajo, Set<Estudiantes> estudianteses) {
       this.cedula = cedula;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.celular = celular;
       this.correo = correo;
       this.ocupacion = ocupacion;
       this.lugarTrabajo = lugarTrabajo;
       this.estudianteses = estudianteses;
    }
   
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public Integer getCelular() {
        return this.celular;
    }
    
    public void setCelular(Integer celular) {
        this.celular = celular;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public String getLugarTrabajo() {
        return this.lugarTrabajo;
    }
    
    public void setLugarTrabajo(String lugarTrabajo) {
        this.lugarTrabajo = lugarTrabajo;
    }
    public Set<Estudiantes> getEstudianteses() {
        return this.estudianteses;
    }
    
    public void setEstudianteses(Set<Estudiantes> estudianteses) {
        this.estudianteses = estudianteses;
    }




}


