package domain;
// Generated 30-ago-2017 15:19:55 by Hibernate Tools 4.3.1



/**
 * Pagomensual generated by hbm2java
 */
public class Pagomensual  implements java.io.Serializable {


     private int cedEstudiante;
     private Estudiantes estudiantes;
     private String mes;
     private Integer anno;
     private Character moroso;

    public Pagomensual() {
    }

	
    public Pagomensual(Estudiantes estudiantes) {
        this.estudiantes = estudiantes;
    }
    public Pagomensual(Estudiantes estudiantes, String mes, Integer anno, Character moroso) {
       this.estudiantes = estudiantes;
       this.mes = mes;
       this.anno = anno;
       this.moroso = moroso;
    }
   
    public int getCedEstudiante() {
        return this.cedEstudiante;
    }
    
    public void setCedEstudiante(int cedEstudiante) {
        this.cedEstudiante = cedEstudiante;
    }
    public Estudiantes getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Estudiantes estudiantes) {
        this.estudiantes = estudiantes;
    }
    public String getMes() {
        return this.mes;
    }
    
    public void setMes(String mes) {
        this.mes = mes;
    }
    public Integer getAnno() {
        return this.anno;
    }
    
    public void setAnno(Integer anno) {
        this.anno = anno;
    }
    public Character getMoroso() {
        return this.moroso;
    }
    
    public void setMoroso(Character moroso) {
        this.moroso = moroso;
    }




}


