package domain;
// Generated 30-ago-2017 15:19:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesores generated by hbm2java
 */
public class Profesores  implements java.io.Serializable {


     private int cedula;
     private Usuarios usuarios;
     private Integer telefono;
     private Integer celular;
     private String correo;
     private Set<Cursos> cursoses = new HashSet<Cursos>(0);

    public Profesores() {
    }

	
    public Profesores(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Profesores(Usuarios usuarios, Integer telefono, Integer celular, String correo, Set<Cursos> cursoses) {
       this.usuarios = usuarios;
       this.telefono = telefono;
       this.celular = celular;
       this.correo = correo;
       this.cursoses = cursoses;
    }
   
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public Integer getCelular() {
        return this.celular;
    }
    
    public void setCelular(Integer celular) {
        this.celular = celular;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set<Cursos> getCursoses() {
        return this.cursoses;
    }
    
    public void setCursoses(Set<Cursos> cursoses) {
        this.cursoses = cursoses;
    }




}


